### ISSUE TITLE
Action nodes wont execute from Standalone

### ISSUE THREAD

**Issue by soctty** [PipeRift/ActionsExtension#1]
Echoing Marketplace comments here because I know the Marketplace isn't always the best about notifications.

Tested in two brand new empty 4.22.2 projects. The plugin never functions in standalone, regardless of play offline/as listen server/as client and single process values, but does work perfectly in normal PIE modes and launch mode. I've been through the source and don't see any immediately obvious cause, and even went so far as to install the plugin to the project itself.

**Comment by muit** [comment]
Thanks for the report!

**Comment by soctty** [comment]
Happy to help! Really excellent plugin. Can't wait to integrate it more fully.

**Comment by muit** [comment]
Well this bug seems super weird. Its like the blueprint node won't execute for some reason.
I may need to ask Epic to see if they know about it.

Executing from c++ seems to be fine because it doesn't use the BP node.

**Comment by soctty** [comment]
I hadn't gotten around to testing from code yet. Such a strangely specific set of circumstances. Almost has to be some sort of engine-side weirdness.

**Comment by muit** [comment]
Turns out Editor wouldn't load on Standalone, so the node wouldn't execute either. Its fixed now and will go out with 1.0a

**Comment by soctty** [comment]
Interesting. I thought preventing that kind of issue was part of the reasoning behind having editor and runtime module declarations. 

Regardless, thanks for nuking it so quickly.

**Comment by muit** [comment]
You are right, its just that apparently standalone compiles blueprints (not like packaged game), so it needs editor. The fact that an editor module fails to load looks like an engine bug in fact.

It was kind of game breaking so got to fix it quick. :)
Thanks for the report
